# Generated by Django 4.2.6 on 2023-11-22 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_team_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='photo',
            field=models.FileField(upload_to='photos/%Y/%m/%d/'),
        ),
    ]
